# Generated by Django 4.2.30 on 2026-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dor_migratoria', models.BooleanField(default=False)),
                ('anorexia', models.BooleanField(default=False)),
                ('nauseas_vomitos', models.BooleanField(default=False)),
                ('dor_fid', models.BooleanField(default=False)),
                ('descompressao_dolorosa', models.BooleanField(default=False)),
                ('temperatura', models.FloatField()),
                ('leucocitos', models.IntegerField()),
                ('neutrofilia', models.BooleanField(default=False)),
                ('score_alvarado', models.IntegerField()),
                ('classificacao_alvarado', models.CharField(max_length=20)),
                ('predicao_knn', models.IntegerField(blank=True, null=True)),
                ('probabilidade_knn', models.FloatField(blank=True, null=True)),
                ('confianca_knn', models.CharField(blank=True, default='', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avaliação Clínica',
                'verbose_name_plural': 'Avaliações Clínicas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
