# Generated by Django 4.2.30 on 2026-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='confianca_svm',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='predicao_svm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='probabilidade_svm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
